FROM alpine-jdk:base

MAINTAINER javaonfly

RUN apk --no-cache add netcat-openbsd

COPY /AuthenticationService/target/AuthenticationService-0.0.1-SNAPSHOT.jar /opt/lib/

COPY Authentication-entrypoint.sh /opt/bin/Authentication-entrypoint.sh

RUN chmod 755 /opt/bin/Authentication-entrypoint.sh
EXPOSE 8081